// Generated by CoffeeScript 1.10.0
(function() {
  jQuery(function() {
    var $, cal_obj, keys, operator;
    $ = jQuery;
    keys = $("#calculator span");
    cal_obj = {
      a: 0,
      b: 0
    };
    operator = "";
    return $.each(keys, function(index, value) {
      return $(this).on("click", function() {
        var btn, display_val, final_result;
        btn = $(this);
        display_val = $("#display_val").text();
        if (btn.prop("id") === "clear") {
          return $("#display_val").text("");
        } else {
          if (btn.prop("id") === "equal") {
            cal_obj.b = $("#display_val").text().replace(cal_obj.a + operator, "");
            if (operator === "+") {
              final_result = parseFloat(cal_obj.a) + parseFloat(cal_obj.b);
            }
            if (operator === "-") {
              final_result = parseFloat(cal_obj.a) - parseFloat(cal_obj.b);
            }
            if (operator === "x") {
              final_result = parseFloat(cal_obj.a) * parseFloat(cal_obj.b);
            }
            if (operator === "/") {
              final_result = parseFloat(cal_obj.a) / parseFloat(cal_obj.b);
            }
            return $("#display_val").text(final_result);
          } else {
            if (btn.hasClass("operator")) {
              cal_obj.a = $("#display_val").text();
              operator = btn.text();
            }
            display_val += btn.text();
            return $("#display_val").text(display_val);
          }
        }
      });
    });
  });

}).call(this);
